/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/HomePage.p.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.WebClient;

@Page
public class HomePage {
    @FindBy(id = "form:home_link")
    public WebElement home;
    @FindBy(id = "form:selectBatchJobExecutions")
    public WebElement batchJobExecutionsLink;
    @FindBy(id = "form:selectBatchJobExecutionContexts")
    public WebElement batchJobExecutionContextsLink;
    @FindBy(id = "form:selectBatchJobExecutionParamss")
    public WebElement batchJobExecutionParamssLink;
    @FindBy(id = "form:selectBatchJobExecutionSeqs")
    public WebElement batchJobExecutionSeqsLink;
    @FindBy(id = "form:selectBatchJobInstances")
    public WebElement batchJobInstancesLink;
    @FindBy(id = "form:selectBatchJobSeqs")
    public WebElement batchJobSeqsLink;
    @FindBy(id = "form:selectBatchStepExecutions")
    public WebElement batchStepExecutionsLink;
    @FindBy(id = "form:selectBatchStepExecutionContexts")
    public WebElement batchStepExecutionContextsLink;
    @FindBy(id = "form:selectBatchStepExecutionSeqs")
    public WebElement batchStepExecutionSeqsLink;
    @FindBy(id = "form:selectDepartments")
    public WebElement departmentsLink;
    @FindBy(id = "form:selectTowns")
    public WebElement townsLink;
    @FindBy(id = "form:switchToFrench")
    public WebElement switchToFrench;
    @FindBy(id = "form:switchToEnglish")
    public WebElement switchToEnglish;
    @FindBy(id = "form:messages")
    public WebElement messagesPanel;

    protected WebClient webClient;

    public void home() {
        webClient.click(home);
    }

    public void switchToEnglish() {
        webClient.click(switchToEnglish);
    }

    public void switchToFrench() {
        webClient.click(switchToFrench);
    }

    public void batchJobExecutions() {
        webClient.click(batchJobExecutionsLink);
    }

    public void batchJobExecutionContexts() {
        webClient.click(batchJobExecutionContextsLink);
    }

    public void batchJobExecutionParamss() {
        webClient.click(batchJobExecutionParamssLink);
    }

    public void batchJobExecutionSeqs() {
        webClient.click(batchJobExecutionSeqsLink);
    }

    public void batchJobInstances() {
        webClient.click(batchJobInstancesLink);
    }

    public void batchJobSeqs() {
        webClient.click(batchJobSeqsLink);
    }

    public void batchStepExecutions() {
        webClient.click(batchStepExecutionsLink);
    }

    public void batchStepExecutionContexts() {
        webClient.click(batchStepExecutionContextsLink);
    }

    public void batchStepExecutionSeqs() {
        webClient.click(batchStepExecutionSeqsLink);
    }

    public void departments() {
        webClient.click(departmentsLink);
    }

    public void towns() {
        webClient.click(townsLink);
    }

    public void hasText(String... values) {
        for (String value : values) {
            webClient.waitUntilTextIsPresent(value);
        }
    }

    public void hasMessage(String... values) {
        for (String value : values) {
            webClient.waitUntilTextIsPresent(messagesPanel, value);
        }
    }

    protected void clickEdit(String value) {
        webClient.clickLinkTitle("Edit " + value);
    }

    protected void clickAdd(String value) {
        webClient.clickLinkTitle("Add " + value);
    }

    protected void clickDelete(String value) {
        webClient.clickLinkTitle("Delete " + value);
    }

    protected void clickRemove(String value) {
        webClient.clickLinkTitle("Remove " + value);
    }

    protected void clickSelect(String value) {
        webClient.clickLinkTitle("Select " + value);
    }
}