/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import static com.bazoud.springbatch.towns.webapp.repository.support.PropertySelector.newPropertySelector;
import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;
import static org.junit.Assert.fail;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.serializer.DefaultDeserializer;
import org.springframework.core.serializer.DefaultSerializer;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance_;
import com.bazoud.springbatch.towns.webapp.repository.support.SearchParameters;

/**
 * Integration test on BatchJobInstanceRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class BatchJobInstanceRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(BatchJobInstanceRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private BatchJobInstanceRepository batchJobInstanceRepository;

    @Inject
    private BatchJobInstanceGenerator batchJobInstanceGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        BatchJobInstance batchJobInstance = batchJobInstanceGenerator.getBatchJobInstance();

        // add it to a Set before saving (force equals/hashcode)
        Set<BatchJobInstance> set = newHashSet(batchJobInstance, batchJobInstance);
        assertThat(set).hasSize(1);

        batchJobInstanceRepository.save(batchJobInstance);
        entityManager.flush();

        // reload it from cache and check equality
        BatchJobInstance model = new BatchJobInstance();
        model.setId(batchJobInstance.getId());
        assertThat(batchJobInstance).isEqualTo(batchJobInstanceRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(batchJobInstance).isEqualTo(batchJobInstanceRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithPropertySelector() {
        BatchJobInstance batchJobInstance = batchJobInstanceGenerator.getBatchJobInstance();

        // add it to a Set before saving (force equals/hashcode)
        Set<BatchJobInstance> set = newHashSet(batchJobInstance, batchJobInstance);
        assertThat(set).hasSize(1);

        batchJobInstanceRepository.save(batchJobInstance);
        entityManager.flush();

        // reload it from cache and check equality
        SearchParameters searchParameters = new SearchParameters();
        searchParameters.property(newPropertySelector(BatchJobInstance_.id).selected(batchJobInstance.getId()));

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters ser = null;
        try {
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            new DefaultSerializer().serialize(searchParameters, stream);
            byte[] bytes = stream.toByteArray();
            ser = (SearchParameters) new DefaultDeserializer().deserialize(new ByteArrayInputStream(bytes));
        } catch (Exception e) {
            fail();
        }

        // pk are equals...
        assertThat(batchJobInstance).isEqualTo(batchJobInstanceRepository.findUnique(ser));
    }

}