/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionSeq;

/**
 * Integration test on BatchStepExecutionSeqRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class BatchStepExecutionSeqRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(BatchStepExecutionSeqRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private BatchStepExecutionSeqRepository batchStepExecutionSeqRepository;

    @Inject
    private BatchStepExecutionSeqGenerator batchStepExecutionSeqGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        BatchStepExecutionSeq batchStepExecutionSeq = batchStepExecutionSeqGenerator.getBatchStepExecutionSeq();

        // add it to a Set before saving (force equals/hashcode)
        Set<BatchStepExecutionSeq> set = newHashSet(batchStepExecutionSeq, batchStepExecutionSeq);
        assertThat(set).hasSize(1);

        batchStepExecutionSeqRepository.save(batchStepExecutionSeq);
        entityManager.flush();

        // reload it from cache and check equality
        BatchStepExecutionSeq model = new BatchStepExecutionSeq();
        model.setId(batchStepExecutionSeq.getId());
        assertThat(batchStepExecutionSeq).isEqualTo(batchStepExecutionSeqRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(batchStepExecutionSeq).isEqualTo(batchStepExecutionSeqRepository.get(model));
    }

}