/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecution;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecutionContext;
import com.bazoud.springbatch.towns.webapp.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class BatchJobExecutionContextGenerator {

    /**
     * Returns a new BatchJobExecutionContext instance filled with random values.
     */
    public BatchJobExecutionContext getBatchJobExecutionContext() {
        BatchJobExecutionContext batchJobExecutionContext = new BatchJobExecutionContext();

        // primary key column must be set manually
        batchJobExecutionContext.setId(ValueGenerator.getUniqueLong());
        // simple attributes follows
        batchJobExecutionContext.setShortContext("a");
        batchJobExecutionContext.setSerializedContext("a");
        // mandatory relation
        BatchJobExecution batchJobExecution = batchJobExecutionGenerator.getBatchJobExecution();
        batchJobExecutionRepository.save(batchJobExecution);
        batchJobExecutionContext.setBatchJobExecution(batchJobExecution);
        return batchJobExecutionContext;
    }

    @Inject
    private BatchJobExecutionRepository batchJobExecutionRepository;
    @Inject
    private BatchJobExecutionGenerator batchJobExecutionGenerator;
}