/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import java.util.Date;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecution;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance;
import com.bazoud.springbatch.towns.webapp.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class BatchJobExecutionGenerator {

    /**
     * Returns a new BatchJobExecution instance filled with random values.
     */
    public BatchJobExecution getBatchJobExecution() {
        BatchJobExecution batchJobExecution = new BatchJobExecution();

        // primary key column must be set manually
        batchJobExecution.setId(ValueGenerator.getUniqueLong());
        // simple attributes follows
        batchJobExecution.setCreateTime(new Date());
        batchJobExecution.setStartTime(new Date());
        batchJobExecution.setEndTime(new Date());
        batchJobExecution.setStatus("a");
        batchJobExecution.setExitCode("a");
        batchJobExecution.setExitMessage("a");
        batchJobExecution.setLastUpdated(new Date());
        // mandatory relation
        BatchJobInstance jobInstance = batchJobInstanceGenerator.getBatchJobInstance();
        batchJobInstanceRepository.save(jobInstance);
        batchJobExecution.setJobInstance(jobInstance);
        return batchJobExecution;
    }

    @Inject
    private BatchJobInstanceRepository batchJobInstanceRepository;
    @Inject
    private BatchJobInstanceGenerator batchJobInstanceGenerator;
}