/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobSeq;
import com.bazoud.springbatch.towns.webapp.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class BatchJobSeqGenerator {

    /**
     * Returns a new BatchJobSeq instance filled with random values.
     */
    public BatchJobSeq getBatchJobSeq() {
        BatchJobSeq batchJobSeq = new BatchJobSeq();

        // primary key column must be set manually
        batchJobSeq.setId(ValueGenerator.getUniqueLong());
        return batchJobSeq;
    }

}