/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(BatchStepExecution.class)
public abstract class BatchStepExecution_ {

    // Raw attributes
    public static volatile SingularAttribute<BatchStepExecution, Long> id;
    public static volatile SingularAttribute<BatchStepExecution, Long> version;
    public static volatile SingularAttribute<BatchStepExecution, String> stepName;
    public static volatile SingularAttribute<BatchStepExecution, Date> startTime;
    public static volatile SingularAttribute<BatchStepExecution, Date> endTime;
    public static volatile SingularAttribute<BatchStepExecution, String> status;
    public static volatile SingularAttribute<BatchStepExecution, Long> commitCount;
    public static volatile SingularAttribute<BatchStepExecution, Long> readCount;
    public static volatile SingularAttribute<BatchStepExecution, Long> filterCount;
    public static volatile SingularAttribute<BatchStepExecution, Long> writeCount;
    public static volatile SingularAttribute<BatchStepExecution, Long> readSkipCount;
    public static volatile SingularAttribute<BatchStepExecution, Long> writeSkipCount;
    public static volatile SingularAttribute<BatchStepExecution, Long> processSkipCount;
    public static volatile SingularAttribute<BatchStepExecution, Long> rollbackCount;
    public static volatile SingularAttribute<BatchStepExecution, String> exitCode;
    public static volatile SingularAttribute<BatchStepExecution, String> exitMessage;
    public static volatile SingularAttribute<BatchStepExecution, Date> lastUpdated;

    // Many to one
    public static volatile SingularAttribute<BatchStepExecution, BatchJobExecution> jobExecution;
}