/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(BatchJobExecution.class)
public abstract class BatchJobExecution_ {

    // Raw attributes
    public static volatile SingularAttribute<BatchJobExecution, Long> id;
    public static volatile SingularAttribute<BatchJobExecution, Long> version;
    public static volatile SingularAttribute<BatchJobExecution, Date> createTime;
    public static volatile SingularAttribute<BatchJobExecution, Date> startTime;
    public static volatile SingularAttribute<BatchJobExecution, Date> endTime;
    public static volatile SingularAttribute<BatchJobExecution, String> status;
    public static volatile SingularAttribute<BatchJobExecution, String> exitCode;
    public static volatile SingularAttribute<BatchJobExecution, String> exitMessage;
    public static volatile SingularAttribute<BatchJobExecution, Date> lastUpdated;

    // Many to one
    public static volatile SingularAttribute<BatchJobExecution, BatchJobInstance> jobInstance;
}