/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "TOWN")
public class Town implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Town.class);

    // Raw attributes
    private Integer id;
    private String department;
    private String name;
    private String nameReal;
    private String postcode;
    private Integer population;
    private Integer area;
    private String longitudeDeg;
    private String latitudeDeg;
    private String longitudeGrd;
    private String latitudeGrd;
    private String longitudeDms;
    private String latitudeDms;
    private Integer zmin;
    private Integer zmax;

    // -- [id] ------------------------

    @Override
    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "ID", precision = 10)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Town id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [department] ------------------------

    @NotEmpty
    @Size(max = 3)
    @Column(name = "DEPARTMENT", nullable = false, length = 3)
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public Town department(String department) {
        setDepartment(department);
        return this;
    }

    // -- [name] ------------------------

    @NotEmpty
    @Size(max = 45)
    @Column(name = "NAME", nullable = false, length = 45)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Town name(String name) {
        setName(name);
        return this;
    }

    // -- [nameReal] ------------------------

    @NotEmpty
    @Size(max = 45)
    @Column(name = "NAME_REAL", nullable = false, length = 45)
    public String getNameReal() {
        return nameReal;
    }

    public void setNameReal(String nameReal) {
        this.nameReal = nameReal;
    }

    public Town nameReal(String nameReal) {
        setNameReal(nameReal);
        return this;
    }

    // -- [postcode] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "POSTCODE", nullable = false)
    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public Town postcode(String postcode) {
        setPostcode(postcode);
        return this;
    }

    // -- [population] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "POPULATION", precision = 10)
    public Integer getPopulation() {
        return population;
    }

    public void setPopulation(Integer population) {
        this.population = population;
    }

    public Town population(Integer population) {
        setPopulation(population);
        return this;
    }

    // -- [area] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "AREA", precision = 10)
    public Integer getArea() {
        return area;
    }

    public void setArea(Integer area) {
        this.area = area;
    }

    public Town area(Integer area) {
        setArea(area);
        return this;
    }

    // -- [longitudeDeg] ------------------------

    @Size(max = 12)
    @Column(name = "LONGITUDE_DEG", length = 12)
    public String getLongitudeDeg() {
        return longitudeDeg;
    }

    public void setLongitudeDeg(String longitudeDeg) {
        this.longitudeDeg = longitudeDeg;
    }

    public Town longitudeDeg(String longitudeDeg) {
        setLongitudeDeg(longitudeDeg);
        return this;
    }

    // -- [latitudeDeg] ------------------------

    @Size(max = 12)
    @Column(name = "LATITUDE_DEG", length = 12)
    public String getLatitudeDeg() {
        return latitudeDeg;
    }

    public void setLatitudeDeg(String latitudeDeg) {
        this.latitudeDeg = latitudeDeg;
    }

    public Town latitudeDeg(String latitudeDeg) {
        setLatitudeDeg(latitudeDeg);
        return this;
    }

    // -- [longitudeGrd] ------------------------

    @Size(max = 12)
    @Column(name = "LONGITUDE_GRD", length = 12)
    public String getLongitudeGrd() {
        return longitudeGrd;
    }

    public void setLongitudeGrd(String longitudeGrd) {
        this.longitudeGrd = longitudeGrd;
    }

    public Town longitudeGrd(String longitudeGrd) {
        setLongitudeGrd(longitudeGrd);
        return this;
    }

    // -- [latitudeGrd] ------------------------

    @Size(max = 12)
    @Column(name = "LATITUDE_GRD", length = 12)
    public String getLatitudeGrd() {
        return latitudeGrd;
    }

    public void setLatitudeGrd(String latitudeGrd) {
        this.latitudeGrd = latitudeGrd;
    }

    public Town latitudeGrd(String latitudeGrd) {
        setLatitudeGrd(latitudeGrd);
        return this;
    }

    // -- [longitudeDms] ------------------------

    @Size(max = 12)
    @Column(name = "LONGITUDE_DMS", length = 12)
    public String getLongitudeDms() {
        return longitudeDms;
    }

    public void setLongitudeDms(String longitudeDms) {
        this.longitudeDms = longitudeDms;
    }

    public Town longitudeDms(String longitudeDms) {
        setLongitudeDms(longitudeDms);
        return this;
    }

    // -- [latitudeDms] ------------------------

    @Size(max = 12)
    @Column(name = "LATITUDE_DMS", length = 12)
    public String getLatitudeDms() {
        return latitudeDms;
    }

    public void setLatitudeDms(String latitudeDms) {
        this.latitudeDms = latitudeDms;
    }

    public Town latitudeDms(String latitudeDms) {
        setLatitudeDms(latitudeDms);
        return this;
    }

    // -- [zmin] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "ZMIN", precision = 10)
    public Integer getZmin() {
        return zmin;
    }

    public void setZmin(Integer zmin) {
        this.zmin = zmin;
    }

    public Town zmin(Integer zmin) {
        setZmin(zmin);
        return this;
    }

    // -- [zmax] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "ZMAX", precision = 10)
    public Integer getZmax() {
        return zmax;
    }

    public void setZmax(Integer zmax) {
        this.zmax = zmax;
    }

    public Town zmax(Integer zmax) {
        setZmax(zmax);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Town withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Town && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Town instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("department", getDepartment()) //
                .add("name", getName()) //
                .add("nameReal", getNameReal()) //
                .add("postcode", getPostcode()) //
                .add("population", getPopulation()) //
                .add("area", getArea()) //
                .add("longitudeDeg", getLongitudeDeg()) //
                .add("latitudeDeg", getLatitudeDeg()) //
                .add("longitudeGrd", getLongitudeGrd()) //
                .add("latitudeGrd", getLatitudeGrd()) //
                .add("longitudeDms", getLongitudeDms()) //
                .add("latitudeDms", getLatitudeDms()) //
                .add("zmin", getZmin()) //
                .add("zmax", getZmax()) //
                .toString();
    }
}