/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchjobexecution;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.DateInput;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EditAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.IntegerInput;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.NoInverseManyToOne;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.StringInput;

@Page
public class BatchJobExecutionEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public BatchJobExecutionEditForm form;
    public BatchJobExecutionEditTabs tabs;

    public static class BatchJobExecutionEditForm extends CustomWebElement {
        public IntegerInput id = new IntegerInput("form:id");
        public DateInput createTime = new DateInput("form:createTime");
        public DateInput startTime = new DateInput("form:startTime");
        public DateInput endTime = new DateInput("form:endTime");
        public StringInput status = new StringInput("form:status");
        public StringInput exitCode = new StringInput("form:exitCode");
        public StringInput exitMessage = new StringInput("form:exitMessage");
        public DateInput lastUpdated = new DateInput("form:lastUpdated");

        public NoInverseManyToOne jobInstance = new NoInverseManyToOne("form:jobInstance");
    };

    public static class BatchJobExecutionEditTabs extends CustomWebElement {
    };
}