/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchjobexecution;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Autocomplete;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.OrderBy;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.SearchForm;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.StringRange;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Table;

@Page
public class BatchJobExecutionSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public BatchJobExecutionSearchOrders orders;
    public BatchJobExecutionSearchForm form;

    public static class BatchJobExecutionSearchOrders extends CustomWebElement {
        public OrderBy id = new OrderBy("batchJobExecution_id");
        public OrderBy jobInstanceId = new OrderBy("batchJobExecution_jobInstanceId");
        public OrderBy createTime = new OrderBy("batchJobExecution_createTime");
        public OrderBy startTime = new OrderBy("batchJobExecution_startTime");
        public OrderBy endTime = new OrderBy("batchJobExecution_endTime");
        public OrderBy status = new OrderBy("batchJobExecution_status");
        public OrderBy exitCode = new OrderBy("batchJobExecution_exitCode");
        public OrderBy exitMessage = new OrderBy("batchJobExecution_exitMessage");
        public OrderBy lastUpdated = new OrderBy("batchJobExecution_lastUpdated");
    }

    public static class BatchJobExecutionSearchForm extends SearchForm {
        public Autocomplete id = new Autocomplete("form:id");
        public StringRange createTime = new StringRange("form:createTime");
        public StringRange startTime = new StringRange("form:startTime");
        public StringRange endTime = new StringRange("form:endTime");
        public Autocomplete status = new Autocomplete("form:status");
        public Autocomplete exitCode = new Autocomplete("form:exitCode");
        public Autocomplete exitMessage = new Autocomplete("form:exitMessage");
        public StringRange lastUpdated = new StringRange("form:lastUpdated");
        public Autocomplete jobInstance = new Autocomplete("form:jobInstanceSelector");
    }
}