/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.bazoud.springbatch.towns.webapp.util.ValueGenerator;

/**
 * Basic tests for BatchJobExecution
 */
@SuppressWarnings("unused")
public class BatchJobExecutionTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        BatchJobExecution model = new BatchJobExecution();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        BatchJobExecution model = new BatchJobExecution();
        model.setId(ValueGenerator.getUniqueLong());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  BatchJobExecution.jobInstance ==> BatchJobInstance.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setJobInstance() {
        BatchJobExecution many = new BatchJobExecution();

        // init
        BatchJobInstance one = new BatchJobInstance();
        one.setId(ValueGenerator.getUniqueLong());
        many.setJobInstance(one);

        // make sure it is propagated properly
        assertThat(many.getJobInstance()).isEqualTo(one);

        // now set it to back to null
        many.setJobInstance(null);

        // make sure null is propagated properly
        assertThat(many.getJobInstance()).isNull();
    }

    /*
     public void equalsUsingPk() {
     BatchJobExecution model1 = new BatchJobExecution();
     BatchJobExecution model2 = new BatchJobExecution();

     Long id = ValueGenerator.getUniqueLong();
     model1.setId(id);
     model2.setId(id);

     model1.setVersion(1l);
     model2.setVersion(1l);

     model1.setCreateTime(new Date());
     model2.setCreateTime(new Date());

     model1.setStartTime(new Date());
     model2.setStartTime(new Date());

     model1.setEndTime(new Date());
     model2.setEndTime(new Date());

     model1.setStatus("a");
     model2.setStatus("a");

     model1.setExitCode("a");
     model2.setExitCode("a");

     model1.setExitMessage("a");
     model2.setExitMessage("a");

     model1.setLastUpdated(new Date());
     model2.setLastUpdated(new Date());
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}