/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.bazoud.springbatch.towns.webapp.util.ValueGenerator;

/**
 * Basic tests for BatchStepExecution
 */
@SuppressWarnings("unused")
public class BatchStepExecutionTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        BatchStepExecution model = new BatchStepExecution();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        BatchStepExecution model = new BatchStepExecution();
        model.setId(ValueGenerator.getUniqueLong());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  BatchStepExecution.jobExecution ==> BatchJobExecution.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setJobExecution() {
        BatchStepExecution many = new BatchStepExecution();

        // init
        BatchJobExecution one = new BatchJobExecution();
        one.setId(ValueGenerator.getUniqueLong());
        many.setJobExecution(one);

        // make sure it is propagated properly
        assertThat(many.getJobExecution()).isEqualTo(one);

        // now set it to back to null
        many.setJobExecution(null);

        // make sure null is propagated properly
        assertThat(many.getJobExecution()).isNull();
    }

    /*
     public void equalsUsingPk() {
     BatchStepExecution model1 = new BatchStepExecution();
     BatchStepExecution model2 = new BatchStepExecution();

     Long id = ValueGenerator.getUniqueLong();
     model1.setId(id);
     model2.setId(id);

     model1.setVersion(1l);
     model2.setVersion(1l);

     model1.setStepName("a");
     model2.setStepName("a");

     model1.setStartTime(new Date());
     model2.setStartTime(new Date());

     model1.setEndTime(new Date());
     model2.setEndTime(new Date());

     model1.setStatus("a");
     model2.setStatus("a");

     model1.setCommitCount(1l);
     model2.setCommitCount(1l);

     model1.setReadCount(1l);
     model2.setReadCount(1l);

     model1.setFilterCount(1l);
     model2.setFilterCount(1l);

     model1.setWriteCount(1l);
     model2.setWriteCount(1l);

     model1.setReadSkipCount(1l);
     model2.setReadSkipCount(1l);

     model1.setWriteSkipCount(1l);
     model2.setWriteSkipCount(1l);

     model1.setProcessSkipCount(1l);
     model2.setProcessSkipCount(1l);

     model1.setRollbackCount(1l);
     model2.setRollbackCount(1l);

     model1.setExitCode("a");
     model2.setExitCode("a");

     model1.setExitMessage("a");
     model2.setExitMessage("a");

     model1.setLastUpdated(new Date());
     model2.setLastUpdated(new Date());
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}