/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.bazoud.springbatch.towns.webapp.util.ValueGenerator;

/**
 * Basic tests for Town
 */
@SuppressWarnings("unused")
public class TownTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Town model = new Town();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Town model = new Town();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
     public void equalsUsingPk() {
     Town model1 = new Town();
     Town model2 = new Town();

     Integer id = ValueGenerator.getUniqueInteger();
     model1.setId(id);
     model2.setId(id);

     model1.setDepartment("a");
     model2.setDepartment("a");

     model1.setName("a");
     model2.setName("a");

     model1.setNameReal("a");
     model2.setNameReal("a");

     model1.setPostcode("a");
     model2.setPostcode("a");

     model1.setPopulation(1);
     model2.setPopulation(1);

     model1.setArea(1);
     model2.setArea(1);

     model1.setLongitudeDeg("a");
     model2.setLongitudeDeg("a");

     model1.setLatitudeDeg("a");
     model2.setLatitudeDeg("a");

     model1.setLongitudeGrd("a");
     model2.setLongitudeGrd("a");

     model1.setLatitudeGrd("a");
     model2.setLatitudeGrd("a");

     model1.setLongitudeDms("a");
     model2.setLongitudeDms("a");

     model1.setLatitudeDms("a");
     model2.setLatitudeDms("a");

     model1.setZmin(1);
     model2.setZmin(1);

     model1.setZmax(1);
     model2.setZmax(1);
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}