/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchjobexecutionparams;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.DateInput;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EditAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.IntegerInput;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.NoInverseManyToOne;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.StringInput;

@Page
public class BatchJobExecutionParamsEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public BatchJobExecutionParamsEditForm form;
    public BatchJobExecutionParamsEditTabs tabs;

    public static class BatchJobExecutionParamsEditForm extends CustomWebElement {
        public StringInput typeCd = new StringInput("form:typeCd");
        public StringInput keyName = new StringInput("form:keyName");
        public StringInput stringVal = new StringInput("form:stringVal");
        public DateInput dateVal = new DateInput("form:dateVal");
        public IntegerInput longVal = new IntegerInput("form:longVal");
        public IntegerInput doubleVal = new IntegerInput("form:doubleVal");
        public StringInput identifying = new StringInput("form:identifying");

        public NoInverseManyToOne batchJobExecution = new NoInverseManyToOne("form:batchJobExecution");
    };

    public static class BatchJobExecutionParamsEditTabs extends CustomWebElement {
    };
}