/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchjobinstance;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Autocomplete;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.OrderBy;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.SearchForm;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Table;

@Page
public class BatchJobInstanceSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public BatchJobInstanceSearchOrders orders;
    public BatchJobInstanceSearchForm form;

    public static class BatchJobInstanceSearchOrders extends CustomWebElement {
        public OrderBy id = new OrderBy("batchJobInstance_id");
        public OrderBy jobName = new OrderBy("batchJobInstance_jobName");
        public OrderBy jobKey = new OrderBy("batchJobInstance_jobKey");
    }

    public static class BatchJobInstanceSearchForm extends SearchForm {
        public Autocomplete id = new Autocomplete("form:id");
        public Autocomplete jobName = new Autocomplete("form:jobName");
        public Autocomplete jobKey = new Autocomplete("form:jobKey");
    }
}