/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchstepexecution;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.DateInput;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EditAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.IntegerInput;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.NoInverseManyToOne;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.StringInput;

@Page
public class BatchStepExecutionEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public BatchStepExecutionEditForm form;
    public BatchStepExecutionEditTabs tabs;

    public static class BatchStepExecutionEditForm extends CustomWebElement {
        public IntegerInput id = new IntegerInput("form:id");
        public StringInput stepName = new StringInput("form:stepName");
        public DateInput startTime = new DateInput("form:startTime");
        public DateInput endTime = new DateInput("form:endTime");
        public StringInput status = new StringInput("form:status");
        public IntegerInput commitCount = new IntegerInput("form:commitCount");
        public IntegerInput readCount = new IntegerInput("form:readCount");
        public IntegerInput filterCount = new IntegerInput("form:filterCount");
        public IntegerInput writeCount = new IntegerInput("form:writeCount");
        public IntegerInput readSkipCount = new IntegerInput("form:readSkipCount");
        public IntegerInput writeSkipCount = new IntegerInput("form:writeSkipCount");
        public IntegerInput processSkipCount = new IntegerInput("form:processSkipCount");
        public IntegerInput rollbackCount = new IntegerInput("form:rollbackCount");
        public StringInput exitCode = new StringInput("form:exitCode");
        public StringInput exitMessage = new StringInput("form:exitMessage");
        public DateInput lastUpdated = new DateInput("form:lastUpdated");

        public NoInverseManyToOne jobExecution = new NoInverseManyToOne("form:jobExecution");
    };

    public static class BatchStepExecutionEditTabs extends CustomWebElement {
    };
}