/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchstepexecution;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Autocomplete;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.OrderBy;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.SearchForm;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.StringRange;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Table;

@Page
public class BatchStepExecutionSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public BatchStepExecutionSearchOrders orders;
    public BatchStepExecutionSearchForm form;

    public static class BatchStepExecutionSearchOrders extends CustomWebElement {
        public OrderBy id = new OrderBy("batchStepExecution_id");
        public OrderBy stepName = new OrderBy("batchStepExecution_stepName");
        public OrderBy jobExecutionId = new OrderBy("batchStepExecution_jobExecutionId");
        public OrderBy startTime = new OrderBy("batchStepExecution_startTime");
        public OrderBy endTime = new OrderBy("batchStepExecution_endTime");
        public OrderBy status = new OrderBy("batchStepExecution_status");
        public OrderBy commitCount = new OrderBy("batchStepExecution_commitCount");
        public OrderBy readCount = new OrderBy("batchStepExecution_readCount");
        public OrderBy filterCount = new OrderBy("batchStepExecution_filterCount");
        public OrderBy writeCount = new OrderBy("batchStepExecution_writeCount");
        public OrderBy readSkipCount = new OrderBy("batchStepExecution_readSkipCount");
        public OrderBy writeSkipCount = new OrderBy("batchStepExecution_writeSkipCount");
        public OrderBy processSkipCount = new OrderBy("batchStepExecution_processSkipCount");
        public OrderBy rollbackCount = new OrderBy("batchStepExecution_rollbackCount");
        public OrderBy exitCode = new OrderBy("batchStepExecution_exitCode");
        public OrderBy exitMessage = new OrderBy("batchStepExecution_exitMessage");
        public OrderBy lastUpdated = new OrderBy("batchStepExecution_lastUpdated");
    }

    public static class BatchStepExecutionSearchForm extends SearchForm {
        public Autocomplete id = new Autocomplete("form:id");
        public Autocomplete stepName = new Autocomplete("form:stepName");
        public StringRange startTime = new StringRange("form:startTime");
        public StringRange endTime = new StringRange("form:endTime");
        public Autocomplete status = new Autocomplete("form:status");
        public StringRange commitCount = new StringRange("form:commitCount");
        public StringRange readCount = new StringRange("form:readCount");
        public StringRange filterCount = new StringRange("form:filterCount");
        public StringRange writeCount = new StringRange("form:writeCount");
        public StringRange readSkipCount = new StringRange("form:readSkipCount");
        public StringRange writeSkipCount = new StringRange("form:writeSkipCount");
        public StringRange processSkipCount = new StringRange("form:processSkipCount");
        public StringRange rollbackCount = new StringRange("form:rollbackCount");
        public Autocomplete exitCode = new Autocomplete("form:exitCode");
        public Autocomplete exitMessage = new Autocomplete("form:exitMessage");
        public StringRange lastUpdated = new StringRange("form:lastUpdated");
        public Autocomplete jobExecution = new Autocomplete("form:jobExecutionSelector");
    }
}