/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.department;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Autocomplete;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.OrderBy;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.SearchForm;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Table;

@Page
public class DepartmentSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public DepartmentSearchOrders orders;
    public DepartmentSearchForm form;

    public static class DepartmentSearchOrders extends CustomWebElement {
        public OrderBy id = new OrderBy("department_id");
        public OrderBy code = new OrderBy("department_code");
        public OrderBy name = new OrderBy("department_name");
        public OrderBy nameUppercase = new OrderBy("department_nameUppercase");
    }

    public static class DepartmentSearchForm extends SearchForm {
        public Autocomplete id = new Autocomplete("form:id");
        public Autocomplete code = new Autocomplete("form:code");
        public Autocomplete name = new Autocomplete("form:name");
        public Autocomplete nameUppercase = new Autocomplete("form:nameUppercase");
    }
}