/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.department;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EditAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.IntegerInput;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.StringInput;

@Page
public class DepartmentEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public DepartmentEditForm form;
    public DepartmentEditTabs tabs;

    public static class DepartmentEditForm extends CustomWebElement {
        public IntegerInput id = new IntegerInput("form:id");
        public StringInput code = new StringInput("form:code");
        public StringInput name = new StringInput("form:name");
        public StringInput nameUppercase = new StringInput("form:nameUppercase");
    };

    public static class DepartmentEditTabs extends CustomWebElement {
    };
}