DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT (
  ID             INT,
  CODE           VARCHAR(3)   NOT NULL,
  NAME           VARCHAR(255) NOT NULL,
  NAME_UPPERCASE VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS TOWN;
CREATE TABLE TOWN (
  ID             INT,
  DEPARTMENT     VARCHAR(3)    NOT NULL,
  NAME           VARCHAR(45)   NOT NULL,
  NAME_REAL      VARCHAR(45)   NOT NULL,
  POSTCODE       VARCHAR(255)  NOT NULL,
  POPULATION     INT,
  AREA           INT,
  LONGITUDE_DEG  VARCHAR(12),
  LATITUDE_DEG   VARCHAR(12),
  LONGITUDE_GRD  VARCHAR(12),
  LATITUDE_GRD   VARCHAR(12),
  LONGITUDE_DMS  VARCHAR(12),
  LATITUDE_DMS   VARCHAR(12),
  ZMIN           INT,
  ZMAX           INT,
  PRIMARY KEY(ID)
);
