/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionContext;
import com.bazoud.springbatch.towns.webapp.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link BatchStepExecutionContext} 
 */
@Named
@Singleton
public class BatchStepExecutionContextRepository extends GenericRepository<BatchStepExecutionContext, Long> {

    public BatchStepExecutionContextRepository() {
        super(BatchStepExecutionContext.class);
    }

    @Override
    public BatchStepExecutionContext getNew() {
        return new BatchStepExecutionContext();
    }

    @Override
    public BatchStepExecutionContext getNewWithDefaults() {
        return getNew().withDefaults();
    }
}