/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecutionParams;
import com.bazoud.springbatch.towns.webapp.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link BatchJobExecutionParams} 
 */
@Named
@Singleton
public class BatchJobExecutionParamsRepository extends GenericRepository<BatchJobExecutionParams, Long> {

    public BatchJobExecutionParamsRepository() {
        super(BatchJobExecutionParams.class);
    }

    @Override
    public BatchJobExecutionParams getNew() {
        return new BatchJobExecutionParams();
    }

    @Override
    public BatchJobExecutionParams getNewWithDefaults() {
        return getNew().withDefaults();
    }
}