/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecution;
import com.bazoud.springbatch.towns.webapp.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link BatchStepExecution} 
 */
@Named
@Singleton
public class BatchStepExecutionRepository extends GenericRepository<BatchStepExecution, Long> {

    public BatchStepExecutionRepository() {
        super(BatchStepExecution.class);
    }

    @Override
    public BatchStepExecution getNew() {
        return new BatchStepExecution();
    }

    @Override
    public BatchStepExecution getNewWithDefaults() {
        return getNew().withDefaults();
    }
}