/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.Department;
import com.bazoud.springbatch.towns.webapp.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link Department} 
 */
@Named
@Singleton
public class DepartmentRepository extends GenericRepository<Department, Integer> {

    public DepartmentRepository() {
        super(Department.class);
    }

    @Override
    public Department getNew() {
        return new Department();
    }

    @Override
    public Department getNewWithDefaults() {
        return getNew().withDefaults();
    }
}