/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecutionParams;
import com.bazoud.springbatch.towns.webapp.printer.BatchJobExecutionParamsPrinter;
import com.bazoud.springbatch.towns.webapp.repository.BatchJobExecutionParamsRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.BatchJobExecutionParamsPermission;

/**
 * Stateless controller for {@link BatchJobExecutionParams} conversation start.
 */
@Named
@Singleton
public class BatchJobExecutionParamsController extends GenericController<BatchJobExecutionParams, Long> {
    public static final String BATCHJOBEXECUTIONPARAMS_EDIT_URI = "/domain/batchJobExecutionParamsEdit.faces";
    public static final String BATCHJOBEXECUTIONPARAMS_SELECT_URI = "/domain/batchJobExecutionParamsSelect.faces";

    @Inject
    public BatchJobExecutionParamsController(BatchJobExecutionParamsRepository batchJobExecutionParamsRepository,
            BatchJobExecutionParamsPermission batchJobExecutionParamsPermission, BatchJobExecutionParamsPrinter batchJobExecutionParamsPrinter) {
        super(batchJobExecutionParamsRepository, batchJobExecutionParamsPermission, batchJobExecutionParamsPrinter, BATCHJOBEXECUTIONPARAMS_SELECT_URI,
                BATCHJOBEXECUTIONPARAMS_EDIT_URI);
    }
}