/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import static com.bazoud.springbatch.towns.webapp.repository.support.PropertySelector.newPropertySelector;

import javax.inject.Named;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecution;
import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionContext;
import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionContext_;
import com.bazoud.springbatch.towns.webapp.repository.support.PropertySelector;
import com.bazoud.springbatch.towns.webapp.repository.support.SearchParameters;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericSearchForm;
import com.bazoud.springbatch.towns.webapp.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link BatchStepExecutionContext}.
 * It exposes a {@link BatchStepExecutionContext} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class BatchStepExecutionContextSearchForm extends GenericSearchForm<BatchStepExecutionContext, Long, BatchStepExecutionContextSearchForm> {
    private static final long serialVersionUID = 1L;
    protected BatchStepExecutionContext batchStepExecutionContext = new BatchStepExecutionContext();
    protected PropertySelector<BatchStepExecutionContext, Long> idSelector = newPropertySelector(BatchStepExecutionContext_.id);
    protected PropertySelector<BatchStepExecutionContext, String> shortContextSelector = newPropertySelector(BatchStepExecutionContext_.shortContext);
    protected PropertySelector<BatchStepExecutionContext, String> serializedContextSelector = newPropertySelector(BatchStepExecutionContext_.serializedContext);
    protected PropertySelector<BatchStepExecutionContext, BatchStepExecution> batchStepExecutionSelector = newPropertySelector(BatchStepExecutionContext_.batchStepExecution);

    public BatchStepExecutionContext getBatchStepExecutionContext() {
        return batchStepExecutionContext;
    }

    @Override
    protected BatchStepExecutionContext getEntity() {
        return getBatchStepExecutionContext();
    }

    @Override
    public BatchStepExecutionContextSearchForm newInstance() {
        return new BatchStepExecutionContextSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.property(idSelector, shortContextSelector, serializedContextSelector);
        sp.property(batchStepExecutionSelector);
        return sp;
    }

    @Override
    public void resetWithOther(BatchStepExecutionContextSearchForm other) {
        this.batchStepExecutionContext = other.getBatchStepExecutionContext();
        this.idSelector = other.getIdSelector();
        this.shortContextSelector = other.getShortContextSelector();
        this.serializedContextSelector = other.getSerializedContextSelector();
        this.batchStepExecutionSelector = other.getBatchStepExecutionSelector();
    }

    // Property selectors
    public PropertySelector<BatchStepExecutionContext, Long> getIdSelector() {
        return idSelector;
    }

    public PropertySelector<BatchStepExecutionContext, String> getShortContextSelector() {
        return shortContextSelector;
    }

    public PropertySelector<BatchStepExecutionContext, String> getSerializedContextSelector() {
        return serializedContextSelector;
    }

    // Relation selectors
    public PropertySelector<BatchStepExecutionContext, BatchStepExecution> getBatchStepExecutionSelector() {
        return batchStepExecutionSelector;
    }
}
