/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionContext;
import com.bazoud.springbatch.towns.webapp.printer.BatchStepExecutionContextPrinter;
import com.bazoud.springbatch.towns.webapp.repository.BatchStepExecutionContextRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.BatchStepExecutionContextPermission;

/**
 * Stateless controller for {@link BatchStepExecutionContext} conversation start.
 */
@Named
@Singleton
public class BatchStepExecutionContextController extends GenericController<BatchStepExecutionContext, Long> {
    public static final String BATCHSTEPEXECUTIONCONTEXT_EDIT_URI = "/domain/batchStepExecutionContextEdit.faces";
    public static final String BATCHSTEPEXECUTIONCONTEXT_SELECT_URI = "/domain/batchStepExecutionContextSelect.faces";

    @Inject
    public BatchStepExecutionContextController(BatchStepExecutionContextRepository batchStepExecutionContextRepository,
            BatchStepExecutionContextPermission batchStepExecutionContextPermission, BatchStepExecutionContextPrinter batchStepExecutionContextPrinter) {
        super(batchStepExecutionContextRepository, batchStepExecutionContextPermission, batchStepExecutionContextPrinter, BATCHSTEPEXECUTIONCONTEXT_SELECT_URI,
                BATCHSTEPEXECUTIONCONTEXT_EDIT_URI);
    }
}