/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionSeq;
import com.bazoud.springbatch.towns.webapp.printer.BatchStepExecutionSeqPrinter;
import com.bazoud.springbatch.towns.webapp.repository.BatchStepExecutionSeqRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.BatchStepExecutionSeqPermission;

/**
 * Stateless controller for {@link BatchStepExecutionSeq} conversation start.
 */
@Named
@Singleton
public class BatchStepExecutionSeqController extends GenericController<BatchStepExecutionSeq, Long> {
    public static final String BATCHSTEPEXECUTIONSEQ_EDIT_URI = "/domain/batchStepExecutionSeqEdit.faces";
    public static final String BATCHSTEPEXECUTIONSEQ_SELECT_URI = "/domain/batchStepExecutionSeqSelect.faces";

    @Inject
    public BatchStepExecutionSeqController(BatchStepExecutionSeqRepository batchStepExecutionSeqRepository,
            BatchStepExecutionSeqPermission batchStepExecutionSeqPermission, BatchStepExecutionSeqPrinter batchStepExecutionSeqPrinter) {
        super(batchStepExecutionSeqRepository, batchStepExecutionSeqPermission, batchStepExecutionSeqPrinter, BATCHSTEPEXECUTIONSEQ_SELECT_URI,
                BATCHSTEPEXECUTIONSEQ_EDIT_URI);
    }
}