/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import static com.bazoud.springbatch.towns.webapp.repository.support.PropertySelector.newPropertySelector;

import javax.inject.Named;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobSeq;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobSeq_;
import com.bazoud.springbatch.towns.webapp.repository.support.PropertySelector;
import com.bazoud.springbatch.towns.webapp.repository.support.SearchParameters;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericSearchForm;
import com.bazoud.springbatch.towns.webapp.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link BatchJobSeq}.
 * It exposes a {@link BatchJobSeq} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class BatchJobSeqSearchForm extends GenericSearchForm<BatchJobSeq, Long, BatchJobSeqSearchForm> {
    private static final long serialVersionUID = 1L;
    protected BatchJobSeq batchJobSeq = new BatchJobSeq();
    protected PropertySelector<BatchJobSeq, Long> idSelector = newPropertySelector(BatchJobSeq_.id);

    public BatchJobSeq getBatchJobSeq() {
        return batchJobSeq;
    }

    @Override
    protected BatchJobSeq getEntity() {
        return getBatchJobSeq();
    }

    @Override
    public BatchJobSeqSearchForm newInstance() {
        return new BatchJobSeqSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.property(idSelector);
        return sp;
    }

    @Override
    public void resetWithOther(BatchJobSeqSearchForm other) {
        this.batchJobSeq = other.getBatchJobSeq();
        this.idSelector = other.getIdSelector();
    }

    // Property selectors
    public PropertySelector<BatchJobSeq, Long> getIdSelector() {
        return idSelector;
    }
}
