/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecutionContext;
import com.bazoud.springbatch.towns.webapp.repository.BatchJobExecutionContextRepository;
import com.bazoud.springbatch.towns.webapp.repository.support.EntityGraphLoader;

/**
 * Preloads the {@link BatchJobExecutionContext} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class BatchJobExecutionContextGraphLoader extends EntityGraphLoader<BatchJobExecutionContext, Long> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected BatchJobExecutionContextGraphLoader() {
        super();
    }

    @Inject
    public BatchJobExecutionContextGraphLoader(BatchJobExecutionContextRepository batchJobExecutionContextRepository) {
        super(batchJobExecutionContextRepository);
    }

    @Override
    public void loadGraph(BatchJobExecutionContext batchJobExecutionContext) {
        loadSingular(batchJobExecutionContext.getBatchJobExecution());
    }
}