/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobSeq;
import com.bazoud.springbatch.towns.webapp.printer.BatchJobSeqPrinter;
import com.bazoud.springbatch.towns.webapp.repository.BatchJobSeqRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.BatchJobSeqPermission;

/**
 * Stateless controller for {@link BatchJobSeq} conversation start.
 */
@Named
@Singleton
public class BatchJobSeqController extends GenericController<BatchJobSeq, Long> {
    public static final String BATCHJOBSEQ_EDIT_URI = "/domain/batchJobSeqEdit.faces";
    public static final String BATCHJOBSEQ_SELECT_URI = "/domain/batchJobSeqSelect.faces";

    @Inject
    public BatchJobSeqController(BatchJobSeqRepository batchJobSeqRepository, BatchJobSeqPermission batchJobSeqPermission, BatchJobSeqPrinter batchJobSeqPrinter) {
        super(batchJobSeqRepository, batchJobSeqPermission, batchJobSeqPrinter, BATCHJOBSEQ_SELECT_URI, BATCHJOBSEQ_EDIT_URI);
    }
}