/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance_;
import com.bazoud.springbatch.towns.webapp.printer.BatchJobInstancePrinter;
import com.bazoud.springbatch.towns.webapp.repository.BatchJobInstanceRepository;
import com.bazoud.springbatch.towns.webapp.repository.support.SearchParameters;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.BatchJobInstancePermission;

/**
 * Stateless controller for {@link BatchJobInstance} conversation start.
 */
@Named
@Singleton
public class BatchJobInstanceController extends GenericController<BatchJobInstance, Long> {
    public static final String BATCHJOBINSTANCE_EDIT_URI = "/domain/batchJobInstanceEdit.faces";
    public static final String BATCHJOBINSTANCE_SELECT_URI = "/domain/batchJobInstanceSelect.faces";

    @Inject
    public BatchJobInstanceController(BatchJobInstanceRepository batchJobInstanceRepository, BatchJobInstancePermission batchJobInstancePermission,
            BatchJobInstancePrinter batchJobInstancePrinter) {
        super(batchJobInstanceRepository, batchJobInstancePermission, batchJobInstancePrinter, BATCHJOBINSTANCE_SELECT_URI, BATCHJOBINSTANCE_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(BatchJobInstance_.jobName)//
                .asc(BatchJobInstance_.jobKey);
    }
}