/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import static com.bazoud.springbatch.towns.webapp.repository.support.PropertySelector.newPropertySelector;
import static com.bazoud.springbatch.towns.webapp.repository.support.Range.newRange;

import java.util.Date;

import javax.inject.Named;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecution;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecution_;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance;
import com.bazoud.springbatch.towns.webapp.repository.support.PropertySelector;
import com.bazoud.springbatch.towns.webapp.repository.support.Range;
import com.bazoud.springbatch.towns.webapp.repository.support.SearchParameters;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericSearchForm;
import com.bazoud.springbatch.towns.webapp.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link BatchJobExecution}.
 * It exposes a {@link BatchJobExecution} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class BatchJobExecutionSearchForm extends GenericSearchForm<BatchJobExecution, Long, BatchJobExecutionSearchForm> {
    private static final long serialVersionUID = 1L;
    protected BatchJobExecution batchJobExecution = new BatchJobExecution();
    protected Range<BatchJobExecution, Date> createTimeRange = newRange(BatchJobExecution_.createTime);
    protected Range<BatchJobExecution, Date> startTimeRange = newRange(BatchJobExecution_.startTime);
    protected Range<BatchJobExecution, Date> endTimeRange = newRange(BatchJobExecution_.endTime);
    protected Range<BatchJobExecution, Date> lastUpdatedRange = newRange(BatchJobExecution_.lastUpdated);
    protected PropertySelector<BatchJobExecution, Long> idSelector = newPropertySelector(BatchJobExecution_.id);
    protected PropertySelector<BatchJobExecution, String> statusSelector = newPropertySelector(BatchJobExecution_.status);
    protected PropertySelector<BatchJobExecution, String> exitCodeSelector = newPropertySelector(BatchJobExecution_.exitCode);
    protected PropertySelector<BatchJobExecution, String> exitMessageSelector = newPropertySelector(BatchJobExecution_.exitMessage);
    protected PropertySelector<BatchJobExecution, BatchJobInstance> jobInstanceSelector = newPropertySelector(BatchJobExecution_.jobInstance);

    public BatchJobExecution getBatchJobExecution() {
        return batchJobExecution;
    }

    @Override
    protected BatchJobExecution getEntity() {
        return getBatchJobExecution();
    }

    @Override
    public BatchJobExecutionSearchForm newInstance() {
        return new BatchJobExecutionSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(createTimeRange, startTimeRange, endTimeRange, lastUpdatedRange);
        sp.property(idSelector, statusSelector, exitCodeSelector, exitMessageSelector);
        sp.property(jobInstanceSelector);
        return sp;
    }

    @Override
    public void resetWithOther(BatchJobExecutionSearchForm other) {
        this.batchJobExecution = other.getBatchJobExecution();
        this.createTimeRange = other.getCreateTimeRange();
        this.startTimeRange = other.getStartTimeRange();
        this.endTimeRange = other.getEndTimeRange();
        this.lastUpdatedRange = other.getLastUpdatedRange();
        this.idSelector = other.getIdSelector();
        this.statusSelector = other.getStatusSelector();
        this.exitCodeSelector = other.getExitCodeSelector();
        this.exitMessageSelector = other.getExitMessageSelector();
        this.jobInstanceSelector = other.getJobInstanceSelector();
    }

    // Ranges
    public Range<BatchJobExecution, Date> getCreateTimeRange() {
        return createTimeRange;
    }

    public Range<BatchJobExecution, Date> getStartTimeRange() {
        return startTimeRange;
    }

    public Range<BatchJobExecution, Date> getEndTimeRange() {
        return endTimeRange;
    }

    public Range<BatchJobExecution, Date> getLastUpdatedRange() {
        return lastUpdatedRange;
    }

    // Property selectors
    public PropertySelector<BatchJobExecution, Long> getIdSelector() {
        return idSelector;
    }

    public PropertySelector<BatchJobExecution, String> getStatusSelector() {
        return statusSelector;
    }

    public PropertySelector<BatchJobExecution, String> getExitCodeSelector() {
        return exitCodeSelector;
    }

    public PropertySelector<BatchJobExecution, String> getExitMessageSelector() {
        return exitMessageSelector;
    }

    // Relation selectors
    public PropertySelector<BatchJobExecution, BatchJobInstance> getJobInstanceSelector() {
        return jobInstanceSelector;
    }
}
