/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecution;
import com.bazoud.springbatch.towns.webapp.printer.BatchStepExecutionPrinter;
import com.bazoud.springbatch.towns.webapp.repository.BatchStepExecutionRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.BatchStepExecutionPermission;

/**
 * Stateless controller for {@link BatchStepExecution} conversation start.
 */
@Named
@Singleton
public class BatchStepExecutionController extends GenericController<BatchStepExecution, Long> {
    public static final String BATCHSTEPEXECUTION_EDIT_URI = "/domain/batchStepExecutionEdit.faces";
    public static final String BATCHSTEPEXECUTION_SELECT_URI = "/domain/batchStepExecutionSelect.faces";

    @Inject
    public BatchStepExecutionController(BatchStepExecutionRepository batchStepExecutionRepository, BatchStepExecutionPermission batchStepExecutionPermission,
            BatchStepExecutionPrinter batchStepExecutionPrinter) {
        super(batchStepExecutionRepository, batchStepExecutionPermission, batchStepExecutionPrinter, BATCHSTEPEXECUTION_SELECT_URI, BATCHSTEPEXECUTION_EDIT_URI);
    }
}