/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecution;
import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionContext;
import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionContext_;
import com.bazoud.springbatch.towns.webapp.repository.BatchStepExecutionContextRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericEditForm;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericToOneAssociation;
import com.bazoud.springbatch.towns.webapp.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link BatchStepExecutionContext}.
 */
@Named
@ConversationContextScoped
public class BatchStepExecutionContextEditForm extends GenericEditForm<BatchStepExecutionContext, Long> {
    @Inject
    protected BatchStepExecutionContextController batchStepExecutionContextController;
    @Inject
    protected BatchStepExecutionController batchStepExecutionController;
    protected GenericToOneAssociation<BatchStepExecution, Long> batchStepExecution;

    @Inject
    public BatchStepExecutionContextEditForm(BatchStepExecutionContextRepository batchStepExecutionContextRepository,
            BatchStepExecutionContextGraphLoader batchStepExecutionContextGraphLoader) {
        super(batchStepExecutionContextRepository, batchStepExecutionContextGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public BatchStepExecutionContext getBatchStepExecutionContext() {
        return getEntity();
    }

    public String print() {
        return batchStepExecutionContextController.print(getBatchStepExecutionContext());
    }

    @PostConstruct
    void setupBatchStepExecutionActions() {
        batchStepExecution = new GenericToOneAssociation<BatchStepExecution, Long>(batchStepExecutionController, BatchStepExecutionContext_.batchStepExecution) {
            @Override
            protected BatchStepExecution get() {
                return getBatchStepExecutionContext().getBatchStepExecution();
            }

            @Override
            protected void set(BatchStepExecution batchStepExecution) {
                getBatchStepExecutionContext().setBatchStepExecution(batchStepExecution);
            }

            @NotNull
            @Override
            public BatchStepExecution getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<BatchStepExecution, Long> getBatchStepExecution() {
        return batchStepExecution;
    }
}
