/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecution;
import com.bazoud.springbatch.towns.webapp.printer.BatchJobExecutionPrinter;
import com.bazoud.springbatch.towns.webapp.repository.BatchJobExecutionRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.BatchJobExecutionPermission;

/**
 * Stateless controller for {@link BatchJobExecution} conversation start.
 */
@Named
@Singleton
public class BatchJobExecutionController extends GenericController<BatchJobExecution, Long> {
    public static final String BATCHJOBEXECUTION_EDIT_URI = "/domain/batchJobExecutionEdit.faces";
    public static final String BATCHJOBEXECUTION_SELECT_URI = "/domain/batchJobExecutionSelect.faces";

    @Inject
    public BatchJobExecutionController(BatchJobExecutionRepository batchJobExecutionRepository, BatchJobExecutionPermission batchJobExecutionPermission,
            BatchJobExecutionPrinter batchJobExecutionPrinter) {
        super(batchJobExecutionRepository, batchJobExecutionPermission, batchJobExecutionPrinter, BATCHJOBEXECUTION_SELECT_URI, BATCHJOBEXECUTION_EDIT_URI);
    }
}