/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance;
import com.bazoud.springbatch.towns.webapp.repository.BatchJobInstanceRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericEditForm;
import com.bazoud.springbatch.towns.webapp.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link BatchJobInstance}.
 */
@Named
@ConversationContextScoped
public class BatchJobInstanceEditForm extends GenericEditForm<BatchJobInstance, Long> {
    @Inject
    protected BatchJobInstanceController batchJobInstanceController;

    @Inject
    public BatchJobInstanceEditForm(BatchJobInstanceRepository batchJobInstanceRepository) {
        super(batchJobInstanceRepository);
    }

    /**
     * The entity to edit/view.
     */
    public BatchJobInstance getBatchJobInstance() {
        return getEntity();
    }

    public String print() {
        return batchJobInstanceController.print(getBatchJobInstance());
    }
}
