/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecution;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericExcelExporter;
import com.bazoud.springbatch.towns.webapp.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link BatchJobExecution} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class BatchJobExecutionExcelExporter extends GenericExcelExporter<BatchJobExecution> {
    @Inject
    protected BatchJobExecutionSearchForm sf;

    public BatchJobExecutionExcelExporter() {
        super("batchJobExecution_id", "batchJobExecution_createTime", "batchJobExecution_startTime", "batchJobExecution_endTime", "batchJobExecution_status",
                "batchJobExecution_exitCode");
    }

    @Override
    protected void fillResultItem(int row, BatchJobExecution item) {
        int col = 0;
        setValue(row, col++, item.getId());
        setDateTime(row, col++, item.getCreateTime());
        setDateTime(row, col++, item.getStartTime());
        setDateTime(row, col++, item.getEndTime());
        setValue(row, col++, item.getStatus());
        setValue(row, col++, item.getExitCode());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setLeftHeader(row, 0, "batchJobExecution_id");
        setValue(row++, 1, sf.getBatchJobExecution().getId());
        setSelectedEntities(row++, 0, "batchJobExecution_jobInstance", sf.getJobInstanceSelector().getSelected());
        setRangeDateTime(row++, 0, "batchJobExecution_createTime", sf.getCreateTimeRange());
        setRangeDateTime(row++, 0, "batchJobExecution_startTime", sf.getStartTimeRange());
        setRangeDateTime(row++, 0, "batchJobExecution_endTime", sf.getEndTimeRange());
        setSelector(row++, 0, "batchJobExecution_status", sf.getStatusSelector());
        setSelector(row++, 0, "batchJobExecution_exitCode", sf.getExitCodeSelector());
        setSelector(row++, 0, "batchJobExecution_exitMessage", sf.getExitMessageSelector());
        setRangeDateTime(row++, 0, "batchJobExecution_lastUpdated", sf.getLastUpdatedRange());
    }
}