/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.bazoud.springbatch.towns.webapp.domain.Department;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericExcelExporter;
import com.bazoud.springbatch.towns.webapp.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Department} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class DepartmentExcelExporter extends GenericExcelExporter<Department> {
    @Inject
    protected DepartmentSearchForm sf;

    public DepartmentExcelExporter() {
        super("department_id", "department_code", "department_name", "department_nameUppercase");
    }

    @Override
    protected void fillResultItem(int row, Department item) {
        int col = 0;
        setValue(row, col++, item.getId());
        setValue(row, col++, item.getCode());
        setValue(row, col++, item.getName());
        setValue(row, col++, item.getNameUppercase());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setLeftHeader(row, 0, "department_id");
        setValue(row++, 1, sf.getDepartment().getId());
        setSelector(row++, 0, "department_code", sf.getCodeSelector());
        setSelector(row++, 0, "department_name", sf.getNameSelector());
        setSelector(row++, 0, "department_nameUppercase", sf.getNameUppercaseSelector());
    }
}