/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.Department;
import com.bazoud.springbatch.towns.webapp.printer.DepartmentPrinter;
import com.bazoud.springbatch.towns.webapp.repository.DepartmentRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.DepartmentPermission;

/**
 * Stateless controller for {@link Department} conversation start.
 */
@Named
@Singleton
public class DepartmentController extends GenericController<Department, Integer> {
    public static final String DEPARTMENT_EDIT_URI = "/domain/departmentEdit.faces";
    public static final String DEPARTMENT_SELECT_URI = "/domain/departmentSelect.faces";

    @Inject
    public DepartmentController(DepartmentRepository departmentRepository, DepartmentPermission departmentPermission, DepartmentPrinter departmentPrinter) {
        super(departmentRepository, departmentPermission, departmentPrinter, DEPARTMENT_SELECT_URI, DEPARTMENT_EDIT_URI);
    }
}