/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.Town;
import com.bazoud.springbatch.towns.webapp.printer.TownPrinter;
import com.bazoud.springbatch.towns.webapp.repository.TownRepository;
import com.bazoud.springbatch.towns.webapp.web.domain.support.GenericController;
import com.bazoud.springbatch.towns.webapp.web.permission.TownPermission;

/**
 * Stateless controller for {@link Town} conversation start.
 */
@Named
@Singleton
public class TownController extends GenericController<Town, Integer> {
    public static final String TOWN_EDIT_URI = "/domain/townEdit.faces";
    public static final String TOWN_SELECT_URI = "/domain/townSelect.faces";

    @Inject
    public TownController(TownRepository townRepository, TownPermission townPermission, TownPrinter townPrinter) {
        super(townRepository, townPermission, townPrinter, TOWN_SELECT_URI, TOWN_EDIT_URI);
    }
}