/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchjobexecutioncontext;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EditAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.NoInverseOneToOne;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.StringInput;

@Page
public class BatchJobExecutionContextEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public BatchJobExecutionContextEditForm form;
    public BatchJobExecutionContextEditTabs tabs;

    public static class BatchJobExecutionContextEditForm extends CustomWebElement {
        public StringInput shortContext = new StringInput("form:shortContext");
        public StringInput serializedContext = new StringInput("form:serializedContext");

        public NoInverseOneToOne batchJobExecution = new NoInverseOneToOne("form:batchJobExecution");
    };

    public static class BatchJobExecutionContextEditTabs extends CustomWebElement {
    };
}