/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchjobexecutionseq;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EditAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.IntegerInput;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;

@Page
public class BatchJobExecutionSeqEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public BatchJobExecutionSeqEditForm form;
    public BatchJobExecutionSeqEditTabs tabs;

    public static class BatchJobExecutionSeqEditForm extends CustomWebElement {
        public IntegerInput id = new IntegerInput("form:id");
    };

    public static class BatchJobExecutionSeqEditTabs extends CustomWebElement {
    };
}