/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.web.selenium.page.batchstepexecutioncontext;

import com.bazoud.springbatch.towns.webapp.web.selenium.support.Page;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Autocomplete;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.CustomWebElement;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.EntityAction;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Messages;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.OrderBy;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.SearchForm;
import com.bazoud.springbatch.towns.webapp.web.selenium.support.elements.Table;

@Page
public class BatchStepExecutionContextSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public BatchStepExecutionContextSearchOrders orders;
    public BatchStepExecutionContextSearchForm form;

    public static class BatchStepExecutionContextSearchOrders extends CustomWebElement {
        public OrderBy id = new OrderBy("batchStepExecutionContext_id");
        public OrderBy shortContext = new OrderBy("batchStepExecutionContext_shortContext");
        public OrderBy serializedContext = new OrderBy("batchStepExecutionContext_serializedContext");
    }

    public static class BatchStepExecutionContextSearchForm extends SearchForm {
        public Autocomplete shortContext = new Autocomplete("form:shortContext");
        public Autocomplete serializedContext = new Autocomplete("form:serializedContext");
        public Autocomplete batchStepExecution = new Autocomplete("form:batchStepExecutionSelector");
    }
}