/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobInstance_;
import com.bazoud.springbatch.towns.webapp.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link BatchJobInstance} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class BatchJobInstancePrinter extends GenericPrinter<BatchJobInstance> {
    public BatchJobInstancePrinter() {
        super(BatchJobInstance.class, BatchJobInstance_.jobName, BatchJobInstance_.jobKey);
    }

    @Override
    public String print(BatchJobInstance batchJobInstance, Locale locale) {
        if (batchJobInstance == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, batchJobInstance.getJobName());
        appendIfNotEmpty(ret, batchJobInstance.getJobKey());
        return ret.toString();
    }
}