/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecution;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecution_;
import com.bazoud.springbatch.towns.webapp.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link BatchJobExecution} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class BatchJobExecutionPrinter extends GenericPrinter<BatchJobExecution> {
    public BatchJobExecutionPrinter() {
        super(BatchJobExecution.class, BatchJobExecution_.status, BatchJobExecution_.exitCode, BatchJobExecution_.exitMessage);
    }

    @Override
    public String print(BatchJobExecution batchJobExecution, Locale locale) {
        if (batchJobExecution == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, batchJobExecution.getStatus());
        appendIfNotEmpty(ret, batchJobExecution.getExitCode());
        appendIfNotEmpty(ret, batchJobExecution.getExitMessage());
        return ret.toString();
    }
}