/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecutionParams;
import com.bazoud.springbatch.towns.webapp.domain.BatchJobExecutionParams_;
import com.bazoud.springbatch.towns.webapp.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link BatchJobExecutionParams} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class BatchJobExecutionParamsPrinter extends GenericPrinter<BatchJobExecutionParams> {
    public BatchJobExecutionParamsPrinter() {
        super(BatchJobExecutionParams.class, BatchJobExecutionParams_.typeCd, BatchJobExecutionParams_.keyName, BatchJobExecutionParams_.identifying);
    }

    @Override
    public String print(BatchJobExecutionParams batchJobExecutionParams, Locale locale) {
        if (batchJobExecutionParams == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, batchJobExecutionParams.getTypeCd());
        appendIfNotEmpty(ret, batchJobExecutionParams.getKeyName());
        appendIfNotEmpty(ret, batchJobExecutionParams.getIdentifying());
        return ret.toString();
    }
}