/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionSeq;
import com.bazoud.springbatch.towns.webapp.domain.BatchStepExecutionSeq_;
import com.bazoud.springbatch.towns.webapp.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link BatchStepExecutionSeq} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class BatchStepExecutionSeqPrinter extends GenericPrinter<BatchStepExecutionSeq> {
    public BatchStepExecutionSeqPrinter() {
        super(BatchStepExecutionSeq.class, BatchStepExecutionSeq_.id);
    }

    @Override
    public String print(BatchStepExecutionSeq batchStepExecutionSeq, Locale locale) {
        if (batchStepExecutionSeq == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, batchStepExecutionSeq.getId());
        return ret.toString();
    }
}