/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.bazoud.springbatch.towns.webapp.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bazoud.springbatch.towns.webapp.domain.Town;
import com.bazoud.springbatch.towns.webapp.domain.Town_;
import com.bazoud.springbatch.towns.webapp.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Town} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class TownPrinter extends GenericPrinter<Town> {
    public TownPrinter() {
        super(Town.class, Town_.name);
    }

    @Override
    public String print(Town town, Locale locale) {
        if (town == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, town.getName());
        return ret.toString();
    }
}